
services:
  # Định nghĩa service cho API
  api:
    container_name: tideofdestiny-api
    build:
      context: .
      dockerfile: TideOfDestiniy.API/Dockerfile
    ports:
      # - "8080:8080" # Ánh xạ port 8080 của máy thật vào port 8080 của container
      - "5168:8080"
      - "7256:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=http://+:8080 # Cấu hình Kestrel để lắng nghe trên port 8080
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      db:
        condition: service_healthy # Chỉ khởi động API khi DB đã sẵn sàng
    networks:
      - tideofdestiny-network

  # Định nghĩa service cho MySQL Database
  db:
    container_name: tideofdestiny-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password

    ports:
      - "3307:3306" # Ánh xạ port 3307 của máy thật vào port 3306 của container
    environment:
      MYSQL_ROOT_PASSWORD: 12345 # <<-- MẬT KHẨU PHẢI KHỚP VỚI appsettings.json
      MYSQL_DATABASE: TideOfDestinyDB
    volumes:
      - mysql_data:/var/lib/mysql # Lưu dữ liệu DB ra ngoài container để không bị mất khi restart
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - tideofdestiny-network

# Định nghĩa volume để lưu trữ dữ liệu DB
volumes:
  mysql_data:
    driver: local

# Định nghĩa network để các container có thể "nói chuyện" với nhau
networks:
  tideofdestiny-network:
    driver: bridge